export const typeBgColors: { [key: string]: string } = {
    fire: "bg-red-500",
    water: "bg-blue-500",
    electric: "bg-yellow-300",
    grass: "bg-green-500",
    psychic: "bg-purple-500",
    ice: "bg-cyan-300",
    fighting: "bg-orange-500",
    poison: "bg-purple-400",
    ground: "bg-yellow-600",
    flying: "bg-sky-400",
    bug: "bg-lime-500",
    rock: "bg-yellow-700",
    ghost: "bg-indigo-600",
    dragon: "bg-purple-600",
    dark: "bg-gray-800",
    steel: "bg-gray-500",
    fairy: "bg-pink-400",
    normal: "bg-gray-400",
    golden: "bg-yellow-600",
};